name: unleash

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: dart pub get
      - name: Format
        run: dart format -o none --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3